project_id = "biyqutgdhqmsdyllgjkp"

[functions.send-status-notification]
verify_jwt = true

[functions.send-reset-password-email]
verify_jwt = false

[functions.send-document-request]
verify_jwt = true

[functions.send-contract]
verify_jwt = true