project_id = "biyqutgdhqmsdyllgjkp"

[functions.send-status-notification]
verify_jwt = false

[functions.send-reset-password-email]
verify_jwt = false

[functions.send-document-request]
verify_jwt = false

[functions.send-contract]
verify_jwt = false

[functions.send-contract-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-application-confirmation]
verify_jwt = false

[functions.send-document-validation]
verify_jwt = false
